"""add rbac group role relationship

Revision ID: 1344a1718e96
Revises: cd8d7f25f9cf
Create Date: 2025-06-10 16:07:05.571206

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1344a1718e96"
down_revision = "cd8d7f25f9cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("admin_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "group", "user", ["admin_id"], ["id"])
    op.add_column("role", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "role", "group", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role", type_="foreignkey")
    op.drop_column("role", "group_id")
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_column("group", "admin_id")
    # ### end Alembic commands ###
