"""Source ID is allowed to be null

Revision ID: 7cd96407889b
Revises: ea5dc3c60f92
Create Date: 2025-07-31 08:23:47.873659

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cd96407889b"
down_revision = "ea5dc3c60f92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subgraph", "resource_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subgraph", "resource_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
