services:
  db:
    image: postgres:12
    restart: always

    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  qdrant:
    image: qdrant/qdrant
    restart: always

    volumes:
      - app-qdrant-data:/qdrant/storage
    environment:
      - QDRANT_SERVICE_API_KEY=${QDRANT_SERVICE_API_KEY?Variable not set}
    ports:
      - 6334:6334
      - 6333:6333

  redis:
    image: redis:alpine
    restart: always

    ports:
      - 6380:6379
    volumes:
      - app-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s



volumes:
  app-db-data:
  app-redis-data:
  app-qdrant-data:
  app-code-workspace:
