services:
  nginx:
    image: nginx:1.25-alpine
    container_name: flock-nginx
    ports:
      - "4433:80"
      # 如果未来需要HTTPS, 可以映射 443 端口
      # - "443:443"
    volumes:
      - ./nginx/flock.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - api
    networks:
      - flock-network 
    restart: always

  frontend:
    image: jimmy1211/flock-frontend:0.1.0
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

    environment:
      - NODE_ENV=production
      - TZ=UTC

      - NEXT_PUBLIC_API_URL=/api
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #   interval: 180s
    #   timeout: 20s
    #   retries: 3
    #   start_period: 30s
    depends_on:
      - api
    networks:
      - flock-network
    restart: always

  api:
    image: jimmy1211/flock-backend:0.1.0
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    # ports:
    #   - 8000:8000
    env_file:
      - .env
    environment:
      - DEBUG=true
      - SERVER_WORKER_AMOUNT=2
      - GUNICORN_TIMEOUT=120
      - TZ=UTC
      - POSTGRES_SERVER=db
      - QDRANT_URL=http://qdrant:6333
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - HOME=/app/data
      - POSTGRES_SERVER=db 
      - POSTGRES_PORT=5432

    volumes:
      - app-upload-data:/app/upload
      - app-backend-model-cache:/app/model_cache
      - app-data:/app/data

      - ./entrypoint.sh:/app/docker-entrypoint-mount.sh
    entrypoint:
      [
        "sh",
        "-c",
        "cp /app/docker-entrypoint-mount.sh /app/entrypoint.sh && sed -i 's/\r$$//' /app/entrypoint.sh && chmod +x /app/entrypoint.sh && /app/entrypoint.sh",
      ]
    depends_on:
      - db
      - redis
      - qdrant
    networks:
      - flock-network
    restart: always
    user: root

  celery_worker:
    image: jimmy1211/flock-backend:0.1.0
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    environment:
      - MODE=worker
      - MIGRATION_ENABLED=true
      - CELERY_AUTO_SCALE=true
      - CELERY_MAX_WORKERS=4
      - CELERY_MIN_WORKERS=1
      - LOG_LEVEL=INFO
      - TZ=UTC
      - POSTGRES_SERVER=db
      - QDRANT_URL=http://qdrant:6333
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - HOME=/app/data
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    user: root
    volumes:
      - app-upload-data:/app/upload
      - app-backend-model-cache:/app/model_cache
      - app-data:/app/data
      - ./entrypoint.sh:/app/docker-entrypoint-mount.sh
    entrypoint:
      [
        "sh",
        "-c",
        "cp /app/docker-entrypoint-mount.sh /app/entrypoint.sh && sed -i 's/\r$//' /app/entrypoint.sh && chmod +x /app/entrypoint.sh && /app/entrypoint.sh",
      ]
    depends_on:
      - redis
      - db
      - qdrant
    networks:
      - flock-network
    restart: always

  db:
    image: postgres:12

    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - flock-network
    restart: always

  qdrant:
    image: qdrant/qdrant

    volumes:
      - app-qdrant-data:/qdrant/storage
    environment:
      - QDRANT_SERVICE_API_KEY=${QDRANT_SERVICE_API_KEY?Variable not set}
    ports:
      - 6334:6334
      - 6333:6333
    networks:
      - flock-network
    restart: always

  redis:
    image: redis:alpine

    ports:
      - 6380:6379
    volumes:
      - app-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - flock-network
    restart: always

networks:
  flock-network:
    driver: bridge

volumes:
  app-db-data:
  app-redis-data:
  app-qdrant-data:
  app-upload-data:
  app-backend-model-cache:
  app-data:
